// This fixed program runs in the selected Linux container; paths never refer to Mac files.
export const projectProgram = String.raw`
const fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const action=process.argv[1],input=JSON.parse(process.argv[2]||'{}'),root=process.argv[3]||'/workspace';
if(!/^\/workspace(?:\/[A-Za-z0-9_.-]+)*$/.test(root)||root.split('/').includes('..')||fs.lstatSync(root).isSymbolicLink())throw Error('Invalid Linux project root');
function safe(relative){if(typeof relative!=='string'||!relative||relative.length>512||relative.startsWith('/')||relative.split('/').some(p=>!p||p==='.'||p==='..'||p==='.git'))throw Error('Invalid project path');const target=path.join(root,relative);let current=root;for(const part of relative.split('/')){current=path.join(current,part);try{if(fs.lstatSync(current).isSymbolicLink())throw Error('Project symlinks cannot be traversed')}catch(error){if(error.code!=='ENOENT')throw error}}return target}
function git(args,allowed=[0]){const result=spawnSync('git',['-C',root,...args],{encoding:'utf8',maxBuffer:16*1024*1024});if(result.error||!allowed.includes(result.status))throw Error('Git operation failed');return result.stdout}
if(action==='import'){if(!Array.isArray(input.files)||input.files.length>200)throw Error('Invalid file set');let total=0;const files=[],conflicts=[];for(const file of input.files){const target=safe(file.path);if(typeof file.content!=='string'||(total+=Buffer.byteLength(file.content))>16*1024*1024)throw Error('Import exceeds limit');if(fs.existsSync(target)){conflicts.push(file.path);continue}files.push({target,content:file.content})}if(conflicts.length){console.log(JSON.stringify({imported:0,conflicts}))}else{for(const file of files){fs.mkdirSync(path.dirname(file.target),{recursive:true});fs.writeFileSync(file.target,file.content,{flag:'wx',mode:0o644})}if(!fs.existsSync(path.join(root,'.git')))git(['init']);console.log(JSON.stringify({imported:files.length}));}}
else if(action==='diff'){if(!fs.existsSync(path.join(root,'.git')))git(['init']);let diff=git(['diff','--no-ext-diff','--']);diff+=git(['diff','--cached','--no-ext-diff','--']);for(const file of git(['ls-files','--others','--exclude-standard','-z']).split('\0').filter(Boolean)){const target=safe(file);if(fs.lstatSync(target).isFile()){const result=spawnSync('git',['diff','--no-index','--no-ext-diff','--','/dev/null',target],{encoding:'utf8',maxBuffer:16*1024*1024});if(![0,1].includes(result.status))throw Error('Untracked diff failed');diff+=result.stdout}}console.log(JSON.stringify({diff}));}
else if(action==='inventory'){let bytes=0,files=0;function scan(directory){for(const name of fs.readdirSync(directory)){const target=path.join(directory,name),info=fs.lstatSync(target);if(info.isSymbolicLink())continue;if(info.isDirectory())scan(target);else if(info.isFile()){bytes+=info.size;files++;if(bytes>200*1024*1024||files>10000)throw Error('Project export exceeds limit')}}}scan(root);console.log(JSON.stringify({bytes,files}));}
else throw Error('Unsupported project operation');`;
